export enum TelegramSessionMode {
  IDLE = 'IDLE',
  COLLECTING_LEARNING = 'COLLECTING_LEARNING',
  AWAITING_EDIT = 'AWAITING_EDIT',
  AWAITING_CUSTOM_SCHEDULE = 'AWAITING_CUSTOM_SCHEDULE',
  AWAITING_CAREER_ROLES = 'AWAITING_CAREER_ROLES',
  AWAITING_CAREER_SKILLS = 'AWAITING_CAREER_SKILLS',
  AWAITING_CAREER_LOCATION = 'AWAITING_CAREER_LOCATION',
  AWAITING_CAREER_SALARY = 'AWAITING_CAREER_SALARY',
  AWAITING_CAREER_WORKTYPE = 'AWAITING_CAREER_WORKTYPE',
  AWAITING_CAREER_EXPERIENCE = 'AWAITING_CAREER_EXPERIENCE',
  AWAITING_CAREER_URLS = 'AWAITING_CAREER_URLS',
  AWAITING_MESSAGE_EDIT = 'AWAITING_MESSAGE_EDIT',
  AWAITING_COVER_EDIT = 'AWAITING_COVER_EDIT',
}

export interface TelegramSession {
  mode: TelegramSessionMode;
  buffer: string[];
  topic?: string;
  pendingPostId?: string;
  learningNoteId?: string;
  pendingJobId?: string;
  pendingPersonId?: string;
  pendingMessageId?: string;
  pendingCoverText?: string;
}
