export enum PostStatus {
  DRAFT = 'DRAFT',
  GENERATING = 'GENERATING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  PUBLISHING = 'PUBLISHING',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
}
