/** Daily tech-content categories (rotation, not a hard rule). */
export const TECH_CATEGORIES = [
  'TECH_FACT',
  'CONCEPT_EXPLAINED',
  'AI_FACT',
  'DEVELOPER_TIP',
  'BACKEND_TIP',
  'DATABASE_TIP',
  'SYSTEM_DESIGN',
  'DEBUGGING_LESSON',
  'PERFORMANCE_TIP',
  'DSA_CONCEPT',
  'ARCHITECTURE_LESSON',
  'TOOL_DISCOVERY',
  'TECH_TREND',
  'COMMON_MISTAKE',
  'MYTH_VS_REALITY',
  'COMPARISON',
  'REAL_WORLD_ENGINEERING',
  'QUESTION_BASED_DISCUSSION',
  'WEEKLY_LEARNING',
  'PROJECT_LESSON',
] as const;

export type TechCategory = (typeof TECH_CATEGORIES)[number];

/** Weekly starting strategy: 0=Sunday … 6=Saturday. History avoids repetition. */
export const WEEKDAY_CATEGORIES: Record<number, TechCategory[]> = {
  0: ['WEEKLY_LEARNING', 'QUESTION_BASED_DISCUSSION', 'PROJECT_LESSON'],
  1: ['BACKEND_TIP', 'CONCEPT_EXPLAINED', 'REAL_WORLD_ENGINEERING'],
  2: ['AI_FACT', 'TECH_TREND', 'COMPARISON'],
  3: ['DEVELOPER_TIP', 'DEBUGGING_LESSON', 'COMMON_MISTAKE'],
  4: ['TECH_FACT', 'TOOL_DISCOVERY', 'MYTH_VS_REALITY'],
  5: ['SYSTEM_DESIGN', 'ARCHITECTURE_LESSON', 'PERFORMANCE_TIP'],
  6: ['TOOL_DISCOVERY', 'DATABASE_TIP', 'DSA_CONCEPT'],
};

/** Curated concrete topics per category (selection pool). */
export const TOPIC_POOLS: Record<TechCategory, string[]> = {
  TECH_FACT: [
    'HTTP/2 multiplexing',
    'PostgreSQL MVCC',
    'Redis single-threaded event loop',
    'JavaScript event loop microtasks',
    'TCP slow start',
  ],
  CONCEPT_EXPLAINED: [
    'NestJS dependency injection',
    'Database indexing',
    'JWT refresh rotation',
    'Backpressure in streams',
    'Idempotency keys',
  ],
  AI_FACT: [
    'LLM tokenization',
    'Vector embeddings',
    'Prompt caching',
    'RAG retrieval basics',
    'Temperature in sampling',
  ],
  DEVELOPER_TIP: [
    'Git bisect debugging',
    'Meaningful commit messages',
    'Code review checklists',
    'Rubber-duck debugging',
    'Reading stack traces',
  ],
  BACKEND_TIP: [
    'Connection pooling',
    'Graceful shutdown',
    'Request timeouts',
    'Cursor pagination',
    'API versioning',
  ],
  DATABASE_TIP: [
    'PostgreSQL partial indexes',
    'N+1 query problem',
    'Redis TTL strategies',
    'Composite index order',
    'Transaction isolation levels',
  ],
  SYSTEM_DESIGN: [
    'Caching layers',
    'Load balancing strategies',
    'Rate limiting algorithms',
    'Message queues',
    'Database sharding basics',
  ],
  DEBUGGING_LESSON: [
    'Heisenbugs from race conditions',
    'Timezone bugs',
    'Off-by-one in pagination',
    'Stale closures in React',
    'Silent float precision loss',
  ],
  PERFORMANCE_TIP: [
    'Avoiding layout thrash',
    'DB query EXPLAIN plans',
    'Debouncing search inputs',
    'Lazy loading routes',
    'Memoizing expensive renders',
  ],
  DSA_CONCEPT: [
    'Hash map collisions',
    'Two-pointer technique',
    'Sliding window',
    'BFS vs DFS trade-offs',
    'Big-O of nested loops',
  ],
  ARCHITECTURE_LESSON: [
    'Monolith vs microservices',
    'Event-driven basics',
    'Hexagonal architecture',
    'CQRS in one paragraph',
    'API gateway responsibilities',
  ],
  TOOL_DISCOVERY: [
    'jq for JSON logs',
    'EXPLAIN ANALYZE',
    'k6 load testing',
    'pg_stat_statements',
    'Git worktrees',
  ],
  TECH_TREND: [
    'Edge runtimes',
    'Server components',
    'Local-first software',
    'Wasm use cases',
    'Platform engineering',
  ],
  COMMON_MISTAKE: [
    'Storing passwords in plain text',
    'Sync blocking the event loop',
    'SELECT * in production',
    'Ignoring promise rejections',
    'Hardcoding secrets',
  ],
  MYTH_VS_REALITY: [
    'More microservices means more scale',
    'NoSQL means no schema',
    'AI writes bug-free code',
    'Comments always help',
    'Premature optimization payoff',
  ],
  COMPARISON: [
    'REST vs GraphQL',
    'PostgreSQL vs MongoDB',
    'Monorepo vs polyrepo',
    'Threads vs event loop',
    'OAuth2 vs session cookies',
  ],
  REAL_WORLD_ENGINEERING: [
    'Incident postmortems',
    'Feature flags',
    'Canary deploys',
    'On-call runbooks',
    'Log levels that help',
  ],
  QUESTION_BASED_DISCUSSION: [
    'Tabs vs spaces in 2026 teams',
    'ORM or raw SQL',
    'Monorepo trade-offs',
    'How do you review AI code',
    'Testing pyramid balance',
  ],
  WEEKLY_LEARNING: [
    'Week in backend learnings',
    'Week in debugging learnings',
    'Week in database learnings',
    'Week in AI learnings',
    'Week in tooling learnings',
  ],
  PROJECT_LESSON: [
    'Scoping an MVP schema',
    'Migrating without downtime',
    'First caching layer',
    'Cleaning up tech debt',
    'Documenting an API',
  ],
};
